name: 'Remote Build - iOS'
description: 'Github implementation of the RNEF Remote Build for iOS'

branding:
  icon: 'box'
  color: 'blue'

inputs:
  github-token:
    description: GitHub Token
    required: true
  working-directory:
    description: 'Working directory for the build command'
    required: false
    default: '.'
  destination:
    description: 'Destination to build to: "simulator" or "device". Using "device" runs "rnef build:ios --archive" and code signing settings (certificate, provisioning profile, keychain password) are required.'
    required: true
    default: 'simulator' # 'simulator' or 'device'
  scheme:
    description: Xcode scheme
    required: true
  configuration:
    description: Xcode configuration
    required: true
  re-sign:
    description: Re-sign the app bundle with new JS bundle
    required: false
  skip-sign:
    description: Skip the signing proccess (used when siging is handled elsewhere)
    required: false
    default: false
  certificate-base64:
    description: '[Device Builds] Base64 encoded P12 file containing Apple certificate (incl. private key)'
    required: false
  certificate-password:
    description: '[Device Builds] Password for the P12 file containing the Apple certificate'
    required: false
  provisioning-profile-base64:
    description: '[Device Builds] Base64 encoded Apple provisioning profile (*.mobileprovision)'
    required: false
  provisioning-profile-name:
    description: '[Device Builds] Name of the Apple provisioning profile (without .mobileprovision extension)'
    required: false
  keychain-password:
    description: '[Device Builds] Password that will protect temporary keychain used for signing (can be a random string)'
    required: false
  rnef-build-extra-params:
    description: 'Extra parameters to pass to "rnef build:ios"'
    required: false
  comment-bot:
    description: 'Whether to send a comment under PR with the link to the generated build'
    required: false
    default: true

outputs:
  artifact-url:
    description: 'URL of the relevant iOS build artifact (could be cached)'
    value: ${{ steps.upload-artifact.outputs.artifact-url || (steps.find-artifact.outcome == 'success' && steps.find-artifact.outputs.artifact-url) }}
  artifact-id:
    description: 'ID of the relevant iOS build artifact (could be cached)'
    value: ${{ steps.upload-artifact.outputs.artifact-id || (steps.find-artifact.outcome == 'success' && steps.find-artifact.outputs.artifact-id) }}

runs:
  using: 'composite'
  steps:
    - name: Validate inputs
      run: |
        if [ "${{ inputs.destination }}" != "simulator" ] && [ "${{ inputs.destination }}" != "device" ]; then
          echo "Invalid input 'destination': '${{ inputs.destination }}'. Allowed values: 'simulator' or 'device'."
          exit 1
        fi

        if [ "${{ inputs.destination }}" == "device" ] && [ "${{ inputs.skip-sign }}" == "false" ]; then
          if [ -z "${{ inputs.certificate-base64 }}" ]; then
            echo "Input 'certificate-base64' is required for device builds."
            exit 1
          fi

          if [ -z "${{ inputs.certificate-password }}" ]; then
            echo "  Input 'certificate-password' is required for device builds."
            exit 1
          fi

          if [ -z "${{ inputs.provisioning-profile-base64 }}" ]; then
            echo "Input 'provisioning-profile-base64' is required for device builds."
            exit 1
          fi

          if [ -z "${{ inputs.provisioning-profile-name }}" ]; then
            echo "Input 'provisioning-profile-name' is required for device builds."
            exit 1
          fi

          if [ -z "${{ inputs.keychain-password }}" ]; then
            echo "Input 'keychain-password' is required for device builds."
            exit 1
          fi
        fi
      shell: bash

    - name: Native Fingerprint
      id: fingerprint
      uses: callstackincubator/ios/.github/actions/rnef-native-fingerprint@v1
      with:
        platform: ios
        working-directory: ${{ inputs.working-directory }}

    - name: Set Artifact Name
      run: |
        echo "ARTIFACT_NAME=rnef-ios-${{ inputs.destination }}-${{ inputs.configuration }}-${{ steps.fingerprint.outputs.hash}}" >> $GITHUB_ENV
      shell: bash

    - name: Find artifact URL
      id: find-artifact
      uses: callstackincubator/ios/.github/actions/find-artifact@v1
      with:
        name: ${{ env.ARTIFACT_NAME }}
        re-sign: ${{ inputs.re-sign }}
        github-token: ${{ inputs.github-token }}
        pr-number: ${{ github.event.pull_request.number }}

    - name: Set Provisioning Profile Path
      run: |
        echo "PROFILE_DIR=$HOME/Library/MobileDevice/Provisioning Profiles" >> $GITHUB_ENV
      shell: bash

    - name: Setup Code Signing (device builds only)
      if: ${{ inputs.re-sign == 'true' || (!steps.find-artifact.outputs.artifact-url && inputs.destination == 'device' && inputs.skip-sign == 'false') }}
      run: |
        # Create temporary keychain
        KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

        security create-keychain -p "${{ inputs.keychain-password }}" $KEYCHAIN_PATH
        security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
        security unlock-keychain -p "${{ inputs.keychain-password }}" $KEYCHAIN_PATH

        # Import certificate to keychain
        CERTIFICATE_PATH=$RUNNER_TEMP/certificate.p12

        echo -n "${{ inputs.certificate-base64 }}" | base64 --decode -o $CERTIFICATE_PATH
        security import $CERTIFICATE_PATH -P "${{ inputs.certificate-password }}" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
        security set-key-partition-list -S apple-tool:,apple: -k "${{ inputs.keychain-password }}" $KEYCHAIN_PATH
        security list-keychain -d user -s $KEYCHAIN_PATH

        # Infer certificate identity
        IDENTITY=$(security find-identity -v -p codesigning $KEYCHAIN_PATH | grep -oE '([0-9A-F]{40})' | head -n 1)
        echo "Certificate identity: $IDENTITY"
        echo "IDENTITY=$IDENTITY" >> $GITHUB_ENV

        # Unpack provisioning profile
        PROFILE_DIR="$HOME/Library/MobileDevice/Provisioning Profiles"
        PROFILE_PATH="$PROFILE_DIR/${{ inputs.provisioning-profile-name }}.mobileprovision"

        mkdir -p "$PROFILE_DIR"
        echo -n "${{ inputs.provisioning-profile-base64 }}" | base64 --decode -o "$PROFILE_PATH"
      shell: bash

    - name: Determine iOS sourceDir
      if: ${{ !steps.find-artifact.outputs.artifact-url }}
      run: |
        JSON_OUTPUT=$(npx rnef config -p ios)
        echo "$JSON_OUTPUT" | jq -r '.project'
        IOS_SOURCE_DIR=$(echo "$JSON_OUTPUT" | jq -r '.project.ios.sourceDir')
        echo "IOS_SOURCE_DIR=$IOS_SOURCE_DIR" >> $GITHUB_ENV
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Build iOS
      if: ${{ !steps.find-artifact.outputs.artifact-url }}
      run: |
        npx rnef build:ios \
          ${{ inputs.destination == 'device' && '--archive' || '' }} \
          --scheme "${{ inputs.scheme }}" \
          --configuration "${{ inputs.configuration }}" \
          --build-folder build \
          --destination ${{ inputs.destination }} \
          ${{ inputs.rnef-build-extra-params }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Find Build Artifact
      if: ${{ !steps.find-artifact.outputs.artifact-url }}
      run: |
        if [ "${{ inputs.destination }}" == "device" ]; then
          IPA_PATH=$(find .rnef/cache/ios/export -maxdepth 1 -name '*.ipa' -type f | head -1)
          echo IPA_PATH $IPA_PATH
          echo "ARTIFACT_PATH=$IPA_PATH" >> $GITHUB_ENV
        else
          # Simulator build: needs to compress with tar, as GH actions drop execute file permission during packing to zip
          APP_PATH=$(find $IOS_SOURCE_DIR/build -name '*.app' -type d | head -1 )
          APP_DIR=$(dirname "$APP_PATH")
          APP_BASENAME=$(basename "$APP_PATH")

          ARTIFACT_PATH="$APP_DIR/app.tar.gz"
          tar -C "$APP_DIR" -czvf "$ARTIFACT_PATH" "$APP_BASENAME"

          echo "ARTIFACT_PATH=$ARTIFACT_PATH" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Download and Unpack IPA
      if: ${{ steps.find-artifact.outputs.artifact-url && inputs.destination == 'device' && inputs.re-sign == 'true' && github.event_name == 'pull_request' }}
      run: |
        curl -L -H "Authorization: token ${{ inputs.github-token }}" \
          -o artifact.zip \
          "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${{ steps.find-artifact.outputs.artifact-id }}/zip"

        unzip artifact.zip -d downloaded-artifacts
        ls -l downloaded-artifacts

        IPA_PATH=$(find downloaded-artifacts -name "*.ipa" -print -quit)
        if [ -z "$IPA_PATH" ]; then
          echo "No IPA file found in the extracted contents."
          exit 1
        fi
        echo "ARTIFACT_PATH=$IPA_PATH" >> $GITHUB_ENV
      shell: bash

    - name: Re-sign IPA
      if: ${{ steps.find-artifact.outputs.artifact-url && inputs.destination == 'device' && inputs.re-sign == 'true' && github.event_name == 'pull_request' }}
      run: |
        npx rnef sign:ios ${{ env.ARTIFACT_PATH }} \
          --build-jsbundle \
          --identity ${{ env.IDENTITY }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    # Find artifact URL again before uploading, as other concurrent workflows could upload the same artifact
    - name: Find artifact URL again before uploading
      id: find-artifact-after-build
      uses: callstackincubator/ios/.github/actions/find-artifact@v1
      with:
        name: ${{ env.ARTIFACT_NAME }}
        re-sign: ${{ inputs.re-sign }}
        github-token: ${{ inputs.github-token }}
        pr-number: ${{ github.event.pull_request.number }}

    - name: Upload Artifact
      id: upload-artifact
      if: ${{ !steps.find-artifact-after-build.outputs.artifact-url || (inputs.re-sign == 'true' && github.event_name == 'pull_request') }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.find-artifact-after-build.outputs.artifact-name || env.ARTIFACT_NAME }}
        path: ${{ env.ARTIFACT_PATH }}
        if-no-files-found: error

    - name: Delete Old Re-Signed Artifacts
      if: ${{ steps.find-artifact-after-build.outputs.artifact-url && inputs.destination == 'device' && inputs.re-sign == 'true' && github.event_name == 'pull_request' }}
      run: |
        for ID in ${{ steps.find-artifact-after-build.outputs.artifact-ids }}; do
          echo "Deleting artifact with ID: $ID"
          curl -X DELETE -H "Authorization: token ${{ inputs.github-token }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$ID"
        done
      shell: bash

    - name: Clean Up Code Signing (device builds only)
      if: ${{ !steps.find-artifact-after-build.outputs.artifact-url && inputs.destination == 'device' && inputs.skip-sign == 'false' }}
      run: |
        KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
        security delete-keychain "$KEYCHAIN_PATH"

        PROFILE_DIR="$HOME/Library/MobileDevice/Provisioning Profiles"
        PROFILE_PATH="$PROFILE_DIR/${{ inputs.provisioning-profile-name }}.mobileprovision"
        rm "$PROFILE_PATH"
      shell: bash

    - name: Post Build
      if: ${{ github.event_name == 'pull_request' && inputs.comment-bot == 'true' }}
      uses: callstackincubator/ios/.github/actions/rnef-post-build@v1
      with:
        title: iOS ${{ inputs.configuration }} ${{ inputs.destination == 'simulator' && 'APP for simulators' || 'IPA for physical devices' }}
        artifact-url: ${{ steps.upload-artifact.outputs.artifact-url || steps.find-artifact-after-build.outputs.artifact-url }}
        github-token: ${{ inputs.github-token }}
